
export const services = [
  {
    title: "AI Solutions",
    slug: "solutions",
    description: `Our AI solutions help businesses automate processes, gain insights, and create personalized experiences. We specialize in developing custom AI models and integrating them into existing systems to help you achieve your business goals.`,
    benefits: [
      "AI Strategy",
      "Machine Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Predictive Analytics",
      "AI Integration",
    ],
    image: "/ai.jpg",
  },
  {
    title: "Branding",
    slug: "branding",
    description: `At the core of our approach, we maintain that brand and UX are closely connected and work together. Our team specializes in creating and representing digital brand identities across channels, providing strategy assistance and guidelines to ensure consistency.`,
    benefits: [
      "Brand Strategy",
      "Brand Architecture",
      "Verbal Identity",
      "Visual Identity",
      "Brand Guidelines",
      "Brand Experiences",
    ],
    image: "/adidas.jpg",
  },
  {
    title: "Digital Products",
    slug: "products",
    description: `We create memorable enterprise and consumer products that drive real business value while delivering exceptional user experiences.`,
    benefits: [
      "Product Strategy",
      "UX/UI Design",
      "Design Systems",
      "Mobile Applications",
      "Web Applications",
      "Product Analytics",
    ],
    image: "/nord.jpg",
  },
  {
    title: "Websites",
    slug: "websites",
    description: `Our portfolio features award-winning websites designed to give users the best experience possible while meeting crucial business objectives.`,
    benefits: [
      "Website Design",
      "Content Strategy",
      "Performance Optimization",
      "SEO Integration",
      "Analytics Setup",
      "Maintenance Services",
    ],
    image: "/airbnb.jpg",
  },
  {
    title: "Content",
    slug: "content",
    description: `We work with brands to identify their unique content needs and deliver custom-made assets at the highest quality.`,
    benefits: [
      "Content Strategy",
      "Copywriting",
      "Video Production",
      "Photography",
      "Animation",
      "Social Media Content",
    ],
    image: "/paypal.jpg",
  },
  {
    title: "Development",
    slug: "development",
    description: `Our designers and developers collaborate closely to create websites and products that provide exceptional user experiences and functionality.`,
    benefits: [
      "Frontend Development",
      "Backend Development",
      "Mobile Development",
      "API Integration",
      "Performance Optimization",
      "Technical Consulting",
    ],
    image: "/redbull.jpg",
  },
];
